'''
This is the correction tool for the text generated by ai agent
if the .json or .yaml has something wrong grammatically or semantically, or it does not follow the logic
of the prompt, this tool will tell us and correct it.
'''