'''
This is the correction tool for the text generated by ai agent
if the .json or .yaml has something wrong grammatically or semantically, or it does not follow the logic
of the prompt, this tool will tell us and correct it.
'''

from __future__ import annotations

from langchain_core.tools import tool

from tools.topology.schema import load_topology
# Resolve paths to the same canonical ai_agent/out/ dir the writer uses,
# so validation finds the files the model just wrote regardless of prefix.
from ai_agent.utils.agent_tools.generation_tool import _resolve_out


@tool
def validate_topology(topology_yaml_path: str, nodes_json_path: str) -> str:
    """Validate a topology.yaml against a nodes.json using Arena's own loader.

    This catches both kinds of error the prompt cares about:
      - structural/grammatical: malformed YAML/JSON, missing required keys,
        unknown metric keys.
      - semantic: a region member or exception endpoint that is not a real node,
        a node listed in two regions, an unsupported version, etc.

    The loader reports path-style locations (e.g. "region_pairs[2]: unknown
    region 'X'") so the agent can fix the exact offending field and re-validate.

    Args:
        topology_yaml_path: path to the topology.yaml to check.
        nodes_json_path: path to the nodes.json to check it against.

    Returns:
        "OK: ..." with a short summary when valid, otherwise
        "INVALID: <path-style error>" describing what to fix.
    """
    try:
        topo = load_topology(_resolve_out(topology_yaml_path), _resolve_out(nodes_json_path))
    except Exception as e:
        return f"INVALID: {e}"

    return (
        f"OK: {len(topo.nodes)} nodes "
        f"({len(topo.workers())} workers), "
        f"{len(topo.regions)} regions, "
        f"{len(topo.region_pairs)} region-pair rules, "
        f"{len(topo.exceptions)} exceptions"
    )
